apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy 
    app: demo-voting-app
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:  
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_HOST_AUTH_METHOD
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: db-data
      spec:
        accessModes: ["ReadWriteOnce"]  
        resources:
          requests:
            storage: 1Gi