apiVersion: v1
kind: Service
metadata:
    name: {{ .Release.Name }}-service
    labels:
        name: {{ .Release.Name }}-service
        app: {{ .Values.app }}
spec:
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
    selector:
        name: {{ .Release.Name }}-pod
        app: {{ .Values.app }}