apiVersion: v1 
kind: Service
metadata:
  name: db
  labels:
    name: {{ .Release.Name }}-service
    app: {{ .Values.app }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
  clusterIP: None   
  selector:
    name: {{ .Release.Name }}-pod
    app: {{ .Values.app }}